import Header from './Header'
import './globals.css'
import { Inter } from 'next/font/google'
import StoreProvider from './services/StoreProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={''}>
        <StoreProvider>
          <Header />
          <div className="bg-gradient-to-r from-indigo-50 via-red-100  to-yellow-50">

            {children}
          </div>
        </StoreProvider>

      </body>
    </html>
  )
}
